name: remember_me
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  provider: ^6.1.1
  shared_preferences: any
  flutter_secure_storage: ^5.0.2
  dio: ^5.4.0
  integration_test:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_widget_from_html: ^0.14.11
  percent_indicator: ^4.2.3
  persistent_bottom_nav_bar: ^5.0.2
  flutter_custom_tabs: ^2.0.0
  intl: ^0.19.0
  http: ^1.2.0
  webview_flutter: ^4.5.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  test: ^1.16.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/Inter-Regular.ttf
